[package]
name = "chess"
version = "0.1.0"
authors = ["DavePearce <david.pearce@ecs.vuw.ac.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
